source "https://rubygems.org"

gem "omnibus", github: "chef/omnibus", branch: "poorndm/add_tinfo_whitelst"
gem "omnibus-software", path: "/omnibus-software"

group :development do
  gem "pry"
  gem "pry-byebug"
  gem "pry-stack_explorer"
end
