AlignArray:
  Enabled: false
ClassLength:
  Enabled: false
CommentAnnotation:
  Enabled: false
Documentation:
  Enabled: false
DoubleNegation:
  Enabled: false
Encoding:
  Enabled: false
EmptyLines:
  Enabled: false
FileName:
  Enabled: false
FormatString:
  Enabled: false
HashSyntax:
  Enabled: true
IfUnlessModifier:
  Enabled: false
LeadingCommentSpace:
  Enabled: false
LineLength:
  Enabled: false
IndentationWidth:
  Enabled: false
IndentHash:
  Enabled: false
MethodCallParentheses:
  Enabled: false
MethodLength:
  Enabled: false
NumericLiterals:
  Enabled: false
PercentLiteralDelimiters:
  Enabled: false
SignalException:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
SpaceBeforeBlockBraces:
  Enabled: false
SpaceInsideBrackets:
  Enabled: false
SpaceInsideParens:
  Enabled: false
SpecialGlobalVars:
  Enabled: false
StringLiterals:
  Enabled: false
TrailingBlankLines:
  Enabled: false
TrailingComma:
  EnforcedStyleForMultiline: comma
UnneededPercentQ:
  Enabled: false
WordArray:
  Enabled: false
UnneededInterpolation:
  Enabled: false
