#!/bin/bash

set -eu

if [[ $BUILDKITE_ORGANIZATION_SLUG != "chef-oss" ]]; then
  export VAULT_ADDR="https://vault.ps.chef.co"
  export VAULT_TOKEN=$(vault login -method=aws -path=aws/private-cd -token-only header_value=vault.ps.chef.co role=ci)
  export ARTIFACTORY_PASSWORD=$(vault kv get -field token account/static/artifactory/buildkite)
  export ARTIFACTORY_TOKEN=$ARTIFACTORY_PASSWORD
  echo "pre-command: ARTIFACTORY_TOKEN length is ${#ARTIFACTORY_TOKEN}"
  echo "pre-command: ARTIFACTORY_PASSWORD length is ${#ARTIFACTORY_PASSWORD}"
fi
